---
title: "Tornados 1950-2015"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard); library(dplyr); library(plotly)

```


Column {.sidebar data-width=150}
-----------------------------------------------------------------------

Select year or press play.

```{r}
sliderInput("year", label="", 1950, 2015, 1974, step = 1, sep='',
                animate=animationOptions(interval=1500, loop=F))
```

Column {data-width=650}
-----------------------------------------------------------------------

### 

```{r}
load('data/tornados.RData')
library(plotly)
g <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  showland = TRUE,
  landcolor = toRGB("gray95"),
  subunitcolor = toRGB("gray80"),
  countrycolor = toRGB("gray80"),
  countrywidth = 0.25,
  subunitwidth = 0.25
)


m <- list(opacity = 0.5,
          symbol = 'dot', 
          strokeOpacity=0)

# note that rstudio will not display this, but saving as webpage will
renderPlotly({
  tornados %>% 
    select(StartLat, StartLon, Year, Fatalities, Injuries, Fscale, Date, State) %>%
    mutate(display = paste0('F', Fscale,'<br>',
                            'Fatalities: ', Fatalities, '<br>',
                            'Injuries: ', Injuries, '<br>',
                            'Date: ', Date, '<br>',
                            'State: ', State, '<br>'
                            ),
           bubsize = scales::rescale(Fscale, c(1, 10))) %>% 
    filter(Year==input$year) %>% 
    na.omit() %>% 
    plot_ly(lat = StartLat, lon = StartLon, 
            color=c(Fscale,5), 
            colors=rev(RColorBrewer::brewer.pal(6, 'RdBu')),
            hoverinfo='text',
            text=display, textfont=list(color='#ff5503'),
            type = 'scattergeo', locationmode = 'USA-states', mode = 'markers',
            marker = list(m[[1]], size = bubsize, colorbar = list(title = "F Scale"))) %>%   #note that if you specify size in the main plotly area, it will incorrectly display the size value along with display
    layout(geo = g, title=input$year)
})

```

Column {data-width=350}
-----------------------------------------------------------------------

### Monthly Counts

```{r}
f <- list(family = "Open Sans",  size = 18,  color = "#7f7f7f")
x <- list(title = "",  titlefont = f, tickvals=paste0(seq(1950,2015,5),'_',1), tickmode='array', tickangle=90)
y <- list(title = "Number of Tornados",  titlefont = f)


renderPlotly({
tornados %>% 
  group_by(Month, Year) %>% 
  summarise(N = length(Fscale)) %>% 
  mutate(YearMonth = paste0(Year, '_', Month)) %>% 
  ungroup() %>% 
  arrange(Year, Month) %>% 
  plot_ly(x=YearMonth, y=N, name='') %>% 
  layout(xaxis=x, yaxis=y, margin=list(b=40)) %>% 
  add_trace(x=YearMonth, y=N, data=filter(., Year==input$year), color='#ff5503', name='', hoverinfo='none') %>% 
  layout(showlegend=F)
})
```

### Yearly Counts

```{r}
require(mgcv)
yearly = tornados %>% 
  group_by(Year) %>% 
  summarise(N = length(Fscale)) %>% 
  arrange(Year)
yearlyfits = fitted(gam(N~s(Year, bs='gp'), data=yearly))
y <- list(title = "Number of Tornados",  titlefont = f, showgrid=F)
f5 = tornados %>% 
  group_by(Year) %>% 
  summarise(F5s = sum(Fscale>=3)) %>% 
  arrange(Year)
y2 <- list(tickfont = list(color = "darkgreen"),overlaying = "y", side = "right", showgrid=F, tickformat='###')
yearly %>% 
  plot_ly(x=Year, y=N, name='Count') %>% 
  add_trace(x=Year, y=yearlyfits, name='Trend') %>% 
  add_trace(x=Year, y=F5s, data=f5, yaxis='y2', name='F3 or greater', opacity=.2) %>% 
  layout(xaxis=x, yaxis=y, yaxis2=y2, showlegend=F, margin=list(r=40))
```

